### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by cristian-5** [artemis-beta/Alethiometer#2]
So, after seeing His Dark Materials - Season 1, I was wondering if in real life we could built a real golden compass. Now, I know its a bit madness but technically if we had a few hundred thousands (or a million) of questions / answers examples with meaning (perhaps on real subjects we already have an answer for), we could feed them into a genetic algorithm which is capable of generating a function that takes in consideration the given data points and approximates an answer for a future prediction. What is the scientific principle that would make the thing work you might ask, and in my opinion this would theoretically work with the right parameters because:

1. History repeats, making the prediction of future events not impossible.
2. One can give different meanings to each symbol, relying a bit on the approximation itself.
3. I'm a computer scientist and it could be a fun project to work on Sundays.

What do you think?

**Comment by zarethrex** [comment]
That is a very interesting concept and very far beyond the capabilities of this little application I made which is more of a toy that a demo of Machine Learning,  so I won't be adding anything like that to this. But certainly if you feel you are on to something I encourage you to give it a go! 👍
