### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by WilliamPerryEvans** [artemis-beta/Alethiometer#3]
This is a really cool project, and a nice design. Is there a way people can check it out by opening up the application? 

Edit: I saw you did put a release there, but only for macOS? Would be cool to see this in action.

**Comment by zarethrex** [comment]
@WilliamPerryEvans thanks! The arms are controlled by using the scroll wheel on the three dials, then you click to "ask your question". I can certainly look into building this on Windows, been a while since I have updated the project so I do not yet know how easy that will be.

**Comment by zarethrex** [comment]
@WilliamPerryEvans Added a Windows release now closing this,

**Comment by WilliamPerryEvans** [comment]
Wow! Thanks so much, it works great 🙏
